default_platform(:android)

platform :android do
  desc "Build debug APK for development"
  lane :build_debug do
    sh(
      command: "flutter build apk --debug --build-number=#{ENV['BUILD_NUMBER']}",
      log: true
    )
  end

  desc "Build debug APK and distribute to Firebase"
  lane :build_and_distribute_firebase do
    build_debug

    apk_path = "build/app/outputs/flutter-apk/app-debug.apk"

    firebase_app_distribution(
      app: ENV["FIREBASE_APP_ID"],
      android_artifact_path: apk_path,
      android_artifact_type: "APK",
      testers: ENV["FIREBASE_TESTERS"],
      service_credentials_json_data: ENV["FIREBASE_SERVICE_ACCOUNT_JSON"]
    )

    UI.success("✅ Build completed and distributed to Firebase!")
  end
end

platform :ios do
  desc "Build IPA and distribute to Firebase App Distribution"
  lane :build_and_distribute_firebase do
    keychain_name = "ci_keychain"
    keychain_password = "ci_keychain_password"

    # Buat keychain sementara di CI
    create_keychain(
      name: keychain_name,
      password: keychain_password,
      default_keychain: true,
      unlock: true,
      timeout: 3600,
      lock_when_sleeps: false
    )

    # Import sertifikat ke keychain yang baru dibuat
    import_certificate(
      certificate_path: "distribution.p12",
      certificate_password: ENV["IOS_P12_PASSWORD"],
      keychain_name: keychain_name,
      keychain_password: keychain_password
    )

    # Install provisioning profile
    install_provisioning_profile(
      path: "AdHoc.mobileprovision"
    )

    # Paksa Xcode pakai manual signing, bukan automatic
    update_code_signing_settings(
      use_automatic_signing: false,
      path: "ios/Runner.xcodeproj",
      team_id: ENV["IOS_TEAM_ID"],
      bundle_identifier: "com.kopianan.Pipeline",
      code_sign_identity: "Apple Distribution",
      profile_name: "AdHoc"
    )

    # Build IPA dengan Flutter
    sh(
      command: "flutter build ipa --release --build-number=#{ENV['BUILD_NUMBER']} --export-options-plist=../ios/ExportOptions.plist",
      log: true
    )

    ipa_path = "../build/ios/ipa/*.ipa"

    firebase_app_distribution(
      app: ENV["FIREBASE_APP_ID_IOS"],
      ipa_path: ipa_path,
      testers: ENV["FIREBASE_TESTERS"],
      service_credentials_json_data: ENV["FIREBASE_SERVICE_ACCOUNT_JSON"]
    )

    UI.success("✅ iOS build completed and distributed to Firebase!")
  end
end